wandb_version: 1

model:
  desc: null
  value: Network_1
quantization:
  desc: null
  value: QAT
fused:
  desc: null
  value: true
batch_size:
  desc: null
  value: 256
num_epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742196939
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
